# -*- coding: utf-8 -*-
"""E commerce

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_eQyY_Tfjf9x8xmMEbxdCRA45o03qPhl
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

df = pd.read_excel("/content/drive/MyDrive/Global_Superstore2.xlsx")
df.head(5)

df.tail()

"""# DATA  UNDERSTANDING"""

df.shape

df.describe()

df.columns

df.duplicated().sum()

df.isnull().sum()

"""# DATA CLEANING"""

# drop postal column
df.drop(columns=['Postal Code'], inplace=True)

# remove duplicates
df.drop_duplicates(inplace=True)

# Convert dates properly

df['Order Date'] = pd.to_datetime(df['Order Date'])

if 'Ship Date' in df.columns:
    df['Ship Date'] = pd.to_datetime(df['Ship Date'])

df[['Order Date', 'Ship Date']].dtypes

"""# Business Analysis

"""

# Create New Columns

# Order Month
df['Order Month'] = df['Order Date'].dt.month

# Order Year
df['Order Year'] = df['Order Date'].dt.year

# Profit Margin (%)
df['Profit Margin'] = (df['Profit'] / df['Sales']) * 100

# Check New Columns
df[['Order Date', 'Order Month', 'Order Year', 'Sales', 'Profit', 'Profit Margin']].head()

total = ['Total Sales', 'Total Profit', 'Total Orders']
values = [total_sales, total_profit, total_orders]

plt.figure(figsize=(8,5))
plt.bar(total, values)
plt.title('Business Performance Overview')
plt.ylabel('Value')
plt.show()

# Total Sales

total_sales = df['Sales'].sum()
total_profit = df['Profit'].sum()
total_orders = df['Order ID'].nunique()
average_order_value = total_sales / total_orders

metrics = ['Total Sales', 'Total Profit', 'Total Orders', 'Average Order Value']
values = [total_sales, total_profit, total_orders, average_order_value]

plt.figure(figsize=(10,6))
plt.bar(metrics, values)
plt.title('Business Performance Overview')
plt.ylabel('Value')
plt.show()

"""# Customer Analysis"""

# Top 10 Customers by Sales

top_customers = df.groupby('Customer Name')['Sales'].sum().sort_values(ascending=False).head(10)

plt.figure(figsize=(10,5))
top_customers.plot(kind='bar')
plt.title('Top 10 Customers by Sales')
plt.xlabel('Customer Name')
plt.ylabel('Total Sales')
plt.xticks(rotation=45)
plt.show()

# Most Valuable Customers by Profit

valuable_customers = df.groupby('Customer Name')['Profit'].sum().sort_values(ascending=False).head(10)

plt.figure(figsize=(10,5))
valuable_customers.plot(kind='bar')
plt.title('Top 10 Most Valuable Customers by Profit')
plt.xlabel('Customer Name')
plt.ylabel('Total Profit')
plt.xticks(rotation=45)
plt.show()

# Customer Segment Analysis

segment_sales = df.groupby('Segment')['Sales'].sum()

plt.figure(figsize=(8,5))
segment_sales.plot(kind='pie', autopct='%1.1f%%')
plt.title('Sales Distribution by Customer Segment')
plt.ylabel('')
plt.show()

"""# Product Analysis"""

# Top 10 Selling Products

top_selling_products = df.groupby('Product Name')['Sales'].sum().sort_values(ascending=False).head(10)

plt.figure(figsize=(12,6))
top_selling_products.plot(kind='bar')
plt.title('Top 10 Selling Products')
plt.xlabel('Product Name')
plt.ylabel('Total Sales')
plt.xticks(rotation=90)
plt.show()

# Top 10 Most Profitable Products

most_profitable_products = df.groupby('Product Name')['Profit'].sum().sort_values(ascending=False).head(10)

plt.figure(figsize=(12,6))
most_profitable_products.plot(kind='bar')
plt.title('Top 10 Most Profitable Products')
plt.xlabel('Product Name')
plt.ylabel('Total Profit')
plt.xticks(rotation=90)
plt.show()

# Worst Performing Products

worst_products = df.groupby('Product Name')['Profit'].sum().sort_values(ascending=True).head(10)

plt.figure(figsize=(12,6))
worst_products.plot(kind='bar')
plt.title('Worst Performing Products')
plt.xlabel('Product Name')
plt.ylabel('Profit')
plt.xticks(rotation=90)
plt.show()

"""# Regional Analysis"""

# Best Region

best_region = df.groupby('Region')['Sales'].sum().sort_values(ascending=False)

plt.figure(figsize=(8,5))
best_region.plot(kind='bar')
plt.title('Sales by Region')
plt.xlabel('Region')
plt.ylabel('Total Sales')
plt.xticks(rotation=45)
plt.show()

# Worst Region

worst_region = df.groupby('Region')['Sales'].sum().sort_values()

plt.figure(figsize=(8,5))
worst_region.plot(kind='bar')
plt.title('Sales by Region')
plt.xlabel('Region')
plt.ylabel('Total Sales')
plt.xticks(rotation=45)
plt.show()

# Highest Profit State

highest_profit_state = df.groupby('State')['Profit'].sum().sort_values(ascending=False).head(10)

plt.figure(figsize=(12,5))
highest_profit_state.plot(kind='bar')
plt.title('Top 10 States by Profit')
plt.xlabel('State')
plt.ylabel('Profit')
plt.xticks(rotation=45)
plt.show()

# Lowest Profit State

lowest_profit_state = df.groupby('State')['Profit'].sum().sort_values().head(10)

plt.figure(figsize=(12,5))
lowest_profit_state.plot(kind='bar')
plt.title('Bottom 10 States by Profit')
plt.xlabel('State')
plt.ylabel('Profit')
plt.xticks(rotation=45)
plt.show()

"""# Time Series Analysis"""

# Monthly Sales Trend

monthly_sales = df.groupby('Order Month')['Sales'].sum()

plt.figure(figsize=(10,5))
monthly_sales.plot(marker='o')
plt.title('Monthly Sales Trend')
plt.xlabel('Month')
plt.ylabel('Total Sales')
plt.grid(True)
plt.show()

# Yearly Sales Growth

yearly_sales = df.groupby('Order Year')['Sales'].sum()

plt.figure(figsize=(8,5))
yearly_sales.plot(kind='bar')
plt.title('Yearly Sales Growth')
plt.xlabel('Year')
plt.ylabel('Total Sales')
plt.xticks(rotation=0)
plt.show()

# Create Quarter Column

df['Quarter'] = df['Order Date'].dt.quarter

seasonal_sales = df.groupby('Quarter')['Sales'].sum()

plt.figure(figsize=(8,5))
seasonal_sales.plot(kind='bar')
plt.title('Seasonal Sales Trends (Quarter-wise)')
plt.xlabel('Quarter')
plt.ylabel('Total Sales')
plt.xticks(rotation=0)
plt.show()